apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image: nicolaka/netshoot
        command: ["sh", "-c", "while true; do echo 'logging...'; sleep 5; done"]
