apiVersion: v1
kind: Pod
metadata:
  name: multitool-pod
spec:
  containers:
    - name: multitool
      image: praqma/network-multitool  # Используем тот же образ, что и в deployment
      ports:
        - containerPort: 8080
      command: ["/bin/sh", "-c", "sleep infinity"]  # Позволяет контейнеру работать бесконечно
  restartPolicy: Always
